// src/Navigation/NavigationComponent.tsx
import * as React from 'react'
import { observer } from 'mobx-react'
import { withInjection } from '../Core/Providers/Injection'
import { Router } from '../Routing/Router'
import { NavigationPresenter } from './NavigationPresenter'
import { LogoutComponent } from '../Authentication/LogoutComponent'

export const NavigationComp = observer((props) => {
  return (
    <div className="navigation-container">
      <div className="navigation-item-header" style={{ backgroundColor: '#5BCA06' }}>
        {props.presenter.viewModel.currentSelectedVisibleName}
      </div>
      {props.presenter.viewModel.menuItems.map((menuItem, i) => {
        return (
          <div
            key={i}
            className="navigation-item"
            style={{
              backgroundColor: '#3DE7CF',
            }}
            onClick={() => {
              props.router.goToId(menuItem.id)
            }}
          >
            {menuItem.visibleName}
          </div>
        )
      })}
      {props.presenter.viewModel.showBack && (
        <div
          className="navigation-item"
          onClick={() => {
            props.presenter.back()
          }}
          style={{ backgroundColor: '#2e91fc' }}
        >
          <span>⬅ </span>Back
        </div>
      )}
      <LogoutComponent />
    </div>
  )
})

export const NavigationComponent = withInjection({
  presenter: NavigationPresenter,
  router: Router,
})(NavigationComp)

// src/Navigation/NavigationComponent.vue
<script setup lang="ts">
import { Observer } from 'mobx-vue-lite'
// import { withInjection } from '../Core/Providers/Injection'
import LogoutComponent from '../Authentication/LogoutComponent.vue'
import { Router } from '../Routing/Router'
import { NavigationPresenter } from './NavigationPresenter'
import { container } from '../AppIOC'

const presenter = container.get(NavigationPresenter)
const router = container.get(Router)
</script>
<template>
  <Observer>
    <div class="navigation-container">
      <div class="navigation-item-header" :style="{ backgroundColor: '#5BCA06' }">
        {{ presenter.viewModel.currentSelectedVisibleName }}
      </div>
      <div
        v-for="menuItem in presenter.viewModel.menuItems"
        class="navigation-item"
        :style="{
              backgroundColor: '#3DE7CF',
            }"
        @click="() => router.goToId(menuItem.id)"
      >
        {{ menuItem.visibleName }}
      </div>


      <div
        v-if="presenter.viewModel.showBack"
        class="navigation-item"
        @click="() => presenter.back()"
        :style="{ backgroundColor: '#2e91fc' }"
      >
        <span>⬅ </span>Back
      </div>

      <LogoutComponent />
    </div>
  </Observer>
</template>
