// src/Core/Messages/MessagesComponent.vue
<script setup lang="ts">
import { Observer } from 'mobx-vue-lite'
import { MessagesPresenter } from './MessagesPresenter'
// { import { withInjection } from '../Providers/Injection' }
// { import { useValidation } from '../Providers/Validation' }
// const [uiMessages] = useValidation()

import { container } from '@/AppIOC.ts'

const vm = container.get(MessagesPresenter).vm;
</script>
<template>

    <div v-for="message in vm.messages" :style="{ backgroundColor: 'red'}">
      - {{ message }}
    </div>

<!--      {props.presenter.messages &&-->
<!--        props.presenter.messages.map((item, i) => {-->
<!--          return (-->
<!--            <div style={{ backgroundColor: 'red' }} key={i}>-->
<!--              {' - '}-->
<!--              {item}-->
<!--            </div>-->
<!--          )-->
<!--        })}-->
<!--      {uiMessages &&-->
<!--        uiMessages.map((item, i) => {-->
<!--          return (-->
<!--            <div style={{ backgroundColor: 'orange' }} key={i}>-->
<!--              {' - '}-->
<!--              {item}-->
<!--            </div>-->
<!--          )-->
<!--        })}-->
</template>

// src/Core/Messages/MessagesComponent.tsx
import * as React from 'react'
import { observer } from 'mobx-react'
import { MessagesPresenter } from '../Messages/MessagesPresenter'
import { withInjection } from '../Providers/Injection'
import { useValidation } from '../Providers/Validation'

export const MessagesComp = observer((props) => {
  const [uiMessages] = useValidation()

  return (
    <>
      {props.presenter.messages &&
        props.presenter.messages.map((item, i) => {
          return (
            <div style={{ backgroundColor: 'red' }} key={i}>
              {' - '}
              {item}
            </div>
          )
        })}
      {uiMessages &&
        uiMessages.map((item, i) => {
          return (
            <div style={{ backgroundColor: 'orange' }} key={i}>
              {' - '}
              {item}
            </div>
          )
        })}
    </>
  )
})

export const MessagesComponent = withInjection({
  presenter: MessagesPresenter,
})(MessagesComp)
